# Generated by Django 4.2.8 on 2023-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Class', models.IntegerField()),
                ('Section', models.CharField(max_length=30)),
                ('Rollno', models.IntegerField()),
                ('Gender', models.CharField(max_length=30)),
                ('Percentage', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
    ]
